/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRuntimeRouteImport } from './routes/diagnostics.runtime'

const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRuntimeRoute = DiagnosticsRuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => DiagnosticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/diagnostics/runtime': typeof DiagnosticsRuntimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/diagnostics/runtime': typeof DiagnosticsRuntimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/diagnostics/runtime': typeof DiagnosticsRuntimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostics' | '/diagnostics/runtime'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostics' | '/diagnostics/runtime'
  id: '__root__' | '/' | '/diagnostics' | '/diagnostics/runtime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/runtime': {
      id: '/diagnostics/runtime'
      path: '/runtime'
      fullPath: '/diagnostics/runtime'
      preLoaderRoute: typeof DiagnosticsRuntimeRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
  }
}

interface DiagnosticsRouteChildren {
  DiagnosticsRuntimeRoute: typeof DiagnosticsRuntimeRoute
}

const DiagnosticsRouteChildren: DiagnosticsRouteChildren = {
  DiagnosticsRuntimeRoute: DiagnosticsRuntimeRoute,
}

const DiagnosticsRouteWithChildren = DiagnosticsRoute._addFileChildren(
  DiagnosticsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
