// This file is automatically generated. Do not edit it directly.
//
// AUTH MIDDLEWARE — Server-side only.
// In a pure SPA build (Vite client), TanStack Start server imports
// don't exist. We guard them behind dynamic imports so the module
// can be imported without crashing the client bundle.
//
// If you are using TanStack Start with SSR, the dynamic imports
// will resolve correctly at runtime.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Factory that creates the auth middleware.
 * Only call this in a server context (TanStack Start server functions).
 * Calling it in a client-only SPA will log a warning and return undefined.
 */
export async function getRequireSupabaseAuth() {
  try {
    const { createMiddleware } = await import("@tanstack/react-start");
    const { getRequest } = await import("@tanstack/react-start/server");

    return createMiddleware({ type: "function" }).server(async ({ next }) => {
      const SUPABASE_URL = process.env.SUPABASE_URL;
      const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

      if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
        throw new Response(
          "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.",
          { status: 500 },
        );
      }

      const request = getRequest();

      if (!request?.headers) {
        throw new Response("Unauthorized: No request headers available", { status: 401 });
      }

      const authHeader = request.headers.get("authorization");

      if (!authHeader) {
        throw new Response("Unauthorized: No authorization header provided", { status: 401 });
      }

      if (!authHeader.startsWith("Bearer ")) {
        throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
      }

      const token = authHeader.replace("Bearer ", "");
      if (!token) {
        throw new Response("Unauthorized: No token provided", { status: 401 });
      }

      const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      });

      const { data, error } = await supabase.auth.getClaims(token);
      if (error || !data?.claims) {
        throw new Response("Unauthorized: Invalid token", { status: 401 });
      }

      if (!data.claims.sub) {
        throw new Response("Unauthorized: No user ID found in token", { status: 401 });
      }

      return next({
        context: {
          supabase,
          userId: data.claims.sub,
          claims: data.claims,
        },
      });
    });
  } catch {
    console.warn(
      "[Auth Middleware] TanStack Start server modules not available. " +
        "This is expected in a client-only SPA build.",
    );
    return undefined;
  }
}
