// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== "undefined" ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // In AURA, users bring their own Supabase credentials at runtime.
    // These env vars are only needed if using the auto-generated integration layer.
    // Return a no-op client that won't crash the app on import.
    console.warn(
      "[Supabase Integration] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY not set. " +
        "The integration client will not be functional. " +
        "AURA uses runtime credentials from StorageSettings instead.",
    );
    // Create a dummy client with placeholder values — it won't be used
    // because AURA's actual Supabase interactions go through lib/supabase.ts
    return createClient<Database>("https://placeholder.supabase.co", "placeholder-key", {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
